FROM golang:1.24.5-alpine3.22@sha256:daae04ebad0c21149979cd8e9db38f565ecefd8547cf4a591240dc1972cf1399 AS build

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o /usr/local/bin/app ./cmd/server/main.go

FROM golang:1.24.5-alpine3.22@sha256:daae04ebad0c21149979cd8e9db38f565ecefd8547cf4a591240dc1972cf1399 AS runtime

COPY --from=build /usr/local/bin/app /usr/local/bin/app
RUN apk add --no-cache curl jq && \
    mkdir -p /etc/ssl/certs && mkdir -p /etc/snowflake/ssl/certs

EXPOSE 80

ENTRYPOINT ["app"]
